baseURL = "/"
title = "QBT - QIWI Blockchain Technologies"
theme = "qbt-official"
copyright = "QBT - QIWI Blockchain Technologies"
relativeURLs = true

[author]
    name = "QBT"

defaultContentLanguage = "en"           # Default language to use
defaultContentLanguageInSubdir = true

[params]
    Description = "site description placed here"
    Author = "QBT - QIWI Blockchain Technologies"
    Keywords = "site keywords placed here"
    email = "info@qiwi.tech"
    phone = "+7 (495) 009-00-09"
    showMenuLanguages = true
    


[languages.en]
  
  languageCode = "en"
  languageName = "English"
  contentDir = "content/en"
  weight = 10

  [languages.en.params]
  address = "4 Shlyuzovaya Embankment 115114 Moscow, Russia"
  slogan_short = "We create a new digital environment for institutions and entire industries."
  slogan_long = "We create a new digital environment for institutions and entire industries. We devise tokenomics of individual projects and create infrastructure and product solutions in the global technology market."
  slogan_long_alter = "We create a new digital environment for institutions and entire industries. We devise tokenomics of individual projects and create infrastructure and product solutions in the global technology market."
  slogan_long_alter2 = "We create a new digital environment for institutions and entire industries. We devise tokenomics of individual projects and create infrastructure and product solutions in the global technology market."


[languages.ru]
  
  languageCode = "ru"
  languageName = "Russian"
  contentDir = "content/ru"
  weight = 20

  [languages.ru.params]
  address = "Москва, Шлюзовая наб., д. 4"
  slogan_short = "Мы создаем новую цифровую среду для институтов и целых индустрий"
  slogan_long = "Мы создаем новую цифровую среду для институтов и целых индустрий. Мы развиваем токеномику проектов компаний, разрабатывая инфраструктурные и продуктовые решения на мировом технологическом рынке."
  slogan_long_alter = "Мы формируем новую цифровую среду для институтов и целых индустрий. Мы разрабатываем токеномику для отдельных проектов и индустриальных компаний,  создавая инфраструктурные и продуктовые решения на мировом технологическом рынке."
  slogan_long_alter2 = "Мы формируем новую цифровую среду для институтов и целых индустрий. Мы развиваем токеномику отдельных проектов и создаем инфраструктурные и продуктовые решения на мировом технологическом рынке. "



[[params.social]]
  title = "Facebook"
  url = "https://www.facebook.com/qiwitech/"
[[params.social]]
  title = "LinkedIn"
  url = "https://www.linkedin.com/company/qiwi-blockchain-technologies/"

